version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Docker Build
          command: | 
            docker build --build-arg AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --build-arg AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -t kix.ocir.io/ax0w66dqmxlm/webtools-go-api .
      - run:
          name: Docker Push
          command: |
            echo ${DOCKER_CONFIG_JSON} > ~/.docker/config.json
            docker push kix.ocir.io/ax0w66dqmxlm/webtools-go-api

workflows:
  build:
    jobs:
      - build